language:
    - c
    - java
jdk:
    - oraclejdk8
os:
    - linux
before_install:
    - sudo apt-get install arduino-core
    - sudo apt-get install arduino-mk
    - sudo apt-get install picocom
    - sudo pip install --upgrade pip
    - sudo pip install ino
install:
    - sudo mkdir -p /var/www/html/
    - sudo cp -R ./src/www /var/www/html/FetchBot
    - cd ./git-submodules/ArduinoJson
    - git submodule init
    - git submodule update
    - cd ..
    - sudo mkdir -p /usr/share/arduino/libraries/
    - sudo cp -R ./ArduinoJson/ /usr/share/arduino/libraries/
    - sudo cp ./ArduinoJson.h /usr/share/arduino/libraries/ArduinoJson.h
    - cd ..
    - cd ./src/arduino-slave-processor/
script:
    - make
    - cd ..
    - cd ..
    - mvn clean package -Dmaven.javadoc.skip=false -DskipTests=true
