language: java
jdk:
    - oraclejdk8
os:
    - linux
install:
    - sudo apt-get arduino-core
    - sudo apt-get arduino-mk
    - sudo apt-get install picocom
    - pip install --upgrade pip
    - pip install ino
    - cd ./git-submodules/ArduinoJson
    - git submodule init
    - git submodule update
    - cd ..
    - sudo mkdir -p /usr/share/arduino/libraries/
    - sudo cp -R ./ArduinoJson/ /usr/share/arduino/libraries/
    - sudo cp ./ArduinoJson.h /usr/share/arduino/libraries/ArduinoJson.h
script:
    - cd ..
    - cd ./src/arduino-slave-processor/
    - make upload
    - cd ..
    - cd ..
    - mvn clean package -Dmaven.javadoc.skip=false -DskipTests=true
    - sudo cp -R ./src/www /var/www/html/FetchBot
