language:
    - java
jdk:
    - oraclejdk8
os:
    - linux
before_install:
    - sudo apt-get update
    - sudo pip install --upgrade pip
    - sudo rm -f -r /var/www/html/FetchBot
    - find ~/bin -name 'fetch-bot*.jar' -exec rm -f {} \;
    - rm -f -r ~/bin/libs/fetch-bot
    - rm -f ~/bin/StartFetchBot.sh
install:
    - sudo apt-get install arduino-core arduino-mk picocom cmake git build-essential libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev python-dev python-numpy
    - sudo pip install ino
before_script:
    - cd ..
    - cd ..
    - rm -f -r ./opencv-3.4.1
    - wget https://github.com/opencv/opencv/archive/3.4.1.zip
    - unzip 3.4.1.zip
    - rm -f 3.4.1.zip
    - cd opencv-3.4.1
    - mkdir -p build
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=RELEASE -D WITH_OPENCL=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_SHARED_LIBS=OFF -D CMAKE_INSTALL_PREFIX=/usr/local ..
    - make -j4
    - sudo make -j4 install
    - mvn install:install-file -Dfile=/usr/local/share/OpenCV/java/opencv-341.jar -DgroupId=opencv -DartifactId=opencv -Dversion=3.4.1 -Dpackaging=jar
    - sudo mkdir -p /usr/share/arduino/libraries/
    - wget https://github.com/bblanchon/ArduinoJson/releases/download/v5.13.1/ArduinoJson-v5.13.1.zip
    - unzip ArduinoJson-v5.13.1.zip
    - rm -f ArduinoJson-v5.13.1.zip
    - sudo cp -r ./ArduinoJson /usr/share/arduino/libraries/
    - rm -f -r ./ArduinoJson
    - cd ./src/arduino-slave-processor/
    - make
    - rm -f -r ./build-uno
    - cd ..
    - cd ..
    - mkdir -p ~/bin
script:
    - mvn clean package -Dmaven.javadoc.skip=false -DskipTests=true
before_cache:
after_success:
after_failure:
before_deploy:
    - cp -r ./target/libs ~/bin
    - cp ./target/fetch-bot-v0.15.0.jar ~/bin/fetch-bot-v0.15.0.jar
    - cp ./src/bash-start.sh ~/bin/StartFetchBot.sh
    - sudo chmod 764 ~/bin/StartFetchBot.sh
    - sudo mkdir -p /var/www/html/
    - sudo cp -R ./src/www /var/www/html/FetchBot
    - sudo chown -R $USER:www-data /var/www/html/FetchBot
    - sudo chmod -R 776 /var/www/html/FetchBot
deploy:
after_deploy:
after_script:
