language:
    - java
jdk:
    - oraclejdk8
os:
    - linux
before_install:
    - sudo apt-add-repository -y ppa:ondrej/php
    - sudo apt-get update -y
    - export ANT_HOME=/usr/share/ant/
    - export PATH=${PATH}:${ANT_HOME}/bin
    - sudo rm -f -r /var/www/html/FetchBot
    - find ~/bin -name 'fetch-bot*.jar' -exec rm -f {} \;
    - rm -f -r ~/bin/libs/fetch-bot
    - rm -f ~/bin/StartFetchBot.sh
install:
    - sudo apt-get install -y ant build-essential cmake git pkg-config
    - sudo apt-get install -y apache2 php7.0 libapache2-mod-php7.0
    - sudo apt-get install -y arduino-core arduino-mk
    - sudo apt-get install -y unclutter
before_script:
    - wget -q https://github.com/opencv/opencv/archive/3.4.1.zip
    - unzip -qq 3.4.1.zip
    - rm -f 3.4.1.zip
    - wget -q https://github.com/opencv/opencv_contrib/archive/3.4.1.zip
    - unzip -qq 3.4.1.zip
    - rm -f 3.4.1.zip
    - cd opencv-3.4.1
    - mkdir -p build
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-3.4.1/modules -D BUILD_NEW_PYTHON_SUPPORT=OFF -D WITH_OPENCL=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_SHARED_LIBS=OFF -D BUILD_EXAMPLES=OFF -D INSTALL_C_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=OFF -DWITH_FFMPEG=OFF ..
    - make
    - sudo make install
    - sudo cp /usr/local/share/OpenCV/java/libopencv_java341.so $JAVA_HOME/jre/lib/amd64/libopencv_java341.so
    - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
    - sudo ldconfig
    - mvn clean install:install-file -Dfile=/usr/local/share/OpenCV/java/opencv-341.jar -DgroupId=opencv -DartifactId=opencv -Dversion=3.4.1 -Dpackaging=jar
    - cd ..
    - cd ..
    - rm -f -r ./opencv-3.4.1
    - rm -f -r ./opencv_contrib-3.4.1
    - sudo mkdir -p /usr/share/arduino/libraries/
    - wget -q https://github.com/bblanchon/ArduinoJson/releases/download/v5.13.1/ArduinoJson-v5.13.1.zip
    - unzip -qq ArduinoJson-v5.13.1.zip
    - rm -f ArduinoJson-v5.13.1.zip
    - sudo cp -r ./ArduinoJson /usr/share/arduino/libraries/
    - rm -f -r ./ArduinoJson
    - cd ./src/arduino-slave-processor/FetchBot
    - make
    - rm -f -r ./build-uno
    - cd ..
    - cd ..
    - cd ..
    - mkdir -p ~/bin
script:
    - mvn clean package -Dmaven.javadoc.skip=false -DskipTests=true
before_cache:
after_success:
after_failure:
before_deploy:
    - cp -r ./target/libs ~/bin
    - cp ./target/fetch-bot-v0.15.1.jar ~/bin/fetch-bot-v0.15.1.jar
    - cp ./src/bash-start.sh ~/bin/StartFetchBot.sh
    - sudo chmod 764 ~/bin/StartFetchBot.sh
    - sudo mkdir -p /var/www/html/
    - sudo cp -R ./src/www /var/www/html/FetchBot
    - sudo chown -R $USER:www-data /var/www/html/FetchBot
    - sudo chmod -R 776 /var/www/html/FetchBot
deploy:
after_deploy:
after_script:
