language:
    - c
    - java
jdk:
    - oraclejdk8
os:
    - linux
before_install:
    - sudo apt-get update
    - sudo pip install --upgrade pip
    - sudo pkill java
    - sudo rm -f -r /var/www/html/FetchBot
    - find ~/bin -name 'fetch-bot*.jar' -exec rm -f {} \;
    - rm -f -r ~/bin/libs/fetch-bot
    - rm -f ~/bin/StartFetchBot.sh
install:
    - sudo apt-get install apache2 php libapache2-mod-php5 arduino-core arduino-mk picocom
    - sudo /etc/init.d/apache2 restart
    - sudo pip install ino
before_script:
    - cd ./git-submodules/ArduinoJson
    - git submodule init
    - git submodule update
    - cd ..
    - sudo mkdir -p /usr/share/arduino/libraries/
    - sudo cp -R ./ArduinoJson/ /usr/share/arduino/libraries/
    - cd ..
    - cd ./src/arduino-slave-processor/
script:
    - make
    - rm -f -r ./build-uno
    - cd ..
    - cd ..
    - mkdir -p ~/bin
    - mvn clean package -Dmaven.javadoc.skip=false -DskipTests=true
before_cache:
after_success:
after_failure:
before_deploy:
    - cp -r ./target/libs ~/bin
    - cp ./target/fetch-bot-v0.14.0.jar ~/bin/fetch-bot-v0.14.0.jar
    - cp ./src/bash-start.sh ~/bin/StartFetchBot.sh
    - sudo chmod 764 ~/bin/StartFetchBot.sh
    - sudo mkdir -p /var/www/html/
    - sudo cp -R ./src/www /var/www/html/FetchBot
    - sudo chown -R $USER:www-data /var/www/html/FetchBot
    - sudo chmod -R 776 /var/www/html/FetchBot
deploy:
after_deploy:
after_script:
